### ISSUE TITLE
Configure the ENS registry address

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-ens#44]
### Overview

The ability to configure the ENS registry address:

### Specification

```toml
[tool.ape.ens]
registry_address = "0x123..."
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
